name = "Cropbox"
uuid = "a904b226-abf1-11e9-2713-059ba252a964"
authors = ["Kyungdahm Yun <tomyun@gmail.com>"]
version = "0.3.52-DEV"

[deps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Graphviz_jll = "3c863552-8265-54e4-a6dc-903eb78fde85"
Highlights = "eafb193a-b7ab-5a9e-9068-77385905fa72"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JuliaInterpreter = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
BlackBoxOptim = "0.5, 0.6"
CSV = "0.8, 0.9, 0.10"
Crayons = "4"
DataFrames = "1"
DataStructures = "0.18"
Distributions = "0.23, 0.24, 0.25"
Gadfly = "1"
Graphs = "1"
Graphviz_jll = "2"
Highlights = "0.5"
Interact = "0.10"
Interpolations = "0.14, 0.15, 0.16"
JuliaInterpreter = "0.9, 0.10"
MacroTools = "0.5"
PolynomialRoots = "1"
PrecompileTools = "1"
ProgressMeter = "1.6"
QuadGK = "2"
Setfield = "1"
StatsBase = "0.33, 0.34"
SymPy = "2"
TimeZones = "1"
TypedTables = "1"
UnicodePlots = "3"
Unitful = "1.7"
julia = "1.6"
