name = "Cropbox"
uuid = "a904b226-abf1-11e9-2713-059ba252a964"
authors = ["Kyungdahm Yun <tomyun@gmail.com>"]
version = "0.2.0"

[deps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Highlights = "eafb193a-b7ab-5a9e-9068-77385905fa72"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Optim = "0.22"
julia = "1.5"
